#Nombre del workflow: Validar HTML
name: Validar HTML
#Evento que desencadena el workflow: cada vez que se hace un push al repositorio
on: [push]
#Este es el proceso que se ejecutará cuando se desencadene el evento
jobs:
  validate:
    runs-on: ubuntu-latest
    #Pasos que se ejecutarán en el proceso
    steps:
      #Descargar el repositorio para poder validar el HTML
      - name: Clonar repositorio
        uses: actions/checkout@v3
      #Se analiza los archivos .html con este validador de HTML de la ruta que uno elija
      - name: Validar HTML
        uses: Cyb3r-Jak3/html5validator-action@v8.0.0
        with:
          root: .